#server:
#  port: 9030

spring:
  application:
    name: seata-order-service  #测试seata
  cloud:
#    alibaba:
#      seata:
#        #自定义事务组名称需要与seata-server中的对应 file.conf ->service-> vgroup_mapping.my_test_tx_group = "fsp_tx_group"
#        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848   #配置nacos 地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql8驱动包
    url: jdbc:mysql://192.168.14.11:3306/seata?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis:
  mapperLocations: classpath:mapper/**/*.xml,classpath:mapper/*.xml    #放在resources下文件夹下时配置
  type-aliases-package: com.grand.springcloud.entity.supplier

management:
  endpoints:
    web:
      exposure:
        include: '*'
