package com.uinfor.mes.si.webservice._7084;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-12-07T11:15:11.258+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "WsEntranceServiceImplService",
                  wsdlLocation = "http://192.168.0.89:7084/ws/mes_web/WS_Security?wsdl",
                  targetNamespace = "http://webservice.si.mes.uinfor.com:7084/")
public class WsEntranceServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.si.mes.uinfor.com:7084/", "WsEntranceServiceImplService");
    public final static QName WsEntranceServiceImplPort = new QName("http://webservice.si.mes.uinfor.com:7084/", "WsEntranceServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.89:7084/ws/mes_web/WS_Security?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsEntranceServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.89:7084/ws/mes_web/WS_Security?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsEntranceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsEntranceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsEntranceServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsEntranceServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsEntranceServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsEntranceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsEntranceService
     */
    @WebEndpoint(name = "WsEntranceServiceImplPort")
    public WsEntranceService getWsEntranceServiceImplPort() {
        return super.getPort(WsEntranceServiceImplPort, WsEntranceService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEntranceService
     */
    @WebEndpoint(name = "WsEntranceServiceImplPort")
    public WsEntranceService getWsEntranceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsEntranceServiceImplPort, WsEntranceService.class, features);
    }

}
