package com.uinfor.mes.si.webservice._7084;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-12-07T11:15:11.188+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://webservice.si.mes.uinfor.com:7084/", name = "WsEntranceService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEntranceService {

    @WebMethod
    @RequestWrapper(localName = "execute", targetNamespace = "http://webservice.si.mes.uinfor.com:7084/", className = "com.uinfor.mes.si.webservice._7084.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://webservice.si.mes.uinfor.com:7084/", className = "com.uinfor.mes.si.webservice._7084.ExecuteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.uinfor.mes.si.webservice._7084.WebServiceResult execute(

        @WebParam(name = "serviceId", targetNamespace = "")
        java.lang.String serviceId,
        @WebParam(name = "jsonData", targetNamespace = "")
        java.lang.String jsonData
    );
}
